name: Selenium tests

on:
  workflow_dispatch:
   inputs:
    test_category:
     description: 'Select test category'
     type: choice
     options:
     - UI_Tests
     - API_Tests
     - All_tests
   required: true

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute TestRail tests
      if: github.event.inputs.test_category == 'UI_Tests'
      run: dotnet test --filter Category=UI_Tests

    - name: Execute Other tests
      if: github.event.inputs.test_category == 'API_Tests'
      run: dotnet test --filter Category=API_Tests

    - name: Execute All tests
      if: github.event.inputs.test_category == 'All_tests'
      run: dotnet test

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: TMS_Diploma/bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
